package com.mironov.psychologicaltest.constants;


public enum ResultsStatus {
    USERS_LOADED,TEST_NAMES_LOADED,LOADING, PRINTED,RESULTS_LOADED,IMPORTED_ANSWERS_FROM_STORAGE,IMPORTED_RESULTS_FROM_STORAGE
}
